### ISSUE TITLE
Research feasibility of removing gulp from helium-typescript

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#86]
## Description:
- gulp is not used often in new projects, most people use npm/native scripts

- References #11

**Comment by codefoster** [comment]
I looked at the feasibility of removing gulp and it should be very easy, so I think we should spawn a new issue to remove it.
In the project, gulp is really just being used to transpile the typescript. It also has a configured task to move json files into the `dist` folder, but that task was not having any effect because there are no .json files in the `src` folder and should we ever want to, that task is easy to accomplish with scripts.
