### ISSUE TITLE
Use import alias pattern instead of relative path references

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#87]
## Description:
- Consider import alias pattern to avoid relative package references in helium-typescript
- Example in config.ts:
![image](https://user-images.githubusercontent.com/3301452/76220091-e32c7200-61e4-11ea-8e3a-74cdd468bc7f.png) 

- References #11

**Comment by codefoster** [comment]
After looking at the codebase with this enhancement in mind, I think it would be of moderate benefit and more so going forward. The effort is small, so we should do it.

**Comment by codefoster** [comment]
I researched this issue more, but one thing I didn't realize (but should probably have) is that you have to install a special npm package so that the path aliases will take effect in the resulting JavaScript code, and I'm not sure I like that level of complexity when I think about a person adopting and grokking this code base. I vote for leaving our paths relative.
