### ISSUE TITLE
Review unit test pattern/framework and controller coverage

### ISSUE THREAD

**Issue by aflinchb** [retaildevcrews/helium-typescript#90]
## Description:
- Check for patterns and frameworks to support unit tests in helium-typescript (currently using jest)
- Provide guidance on unit testing the controllers 
- Implement unit tests on controllers (can be broken out into a separate task/issue)
- References #11

**Comment by codefoster** [comment]
Just talked with Anne about this one.
We decided (unless anyone disagrees) to stick with Jest as the test framework because...
 - it's already in place
 - it's a bit simpler than mocha/chai
 - we don't need the power and configurability of mocha/chai for this project

We also decided that for testing controllers, we would fetch the test data directly from the raw json files in the `/imdb` repo.

I'll begin this work next.
